const nearest=(x,y,enemies,range=Infinity)=>{let best=null,bd=range*range;for(const e of enemies){if(e.hp<=0||e.targetable===false)continue;const d=(e.x-x)**2+(e.y-y)**2;if(d<bd){bd=d;best=e}}return best};
const damageNear=(x,y,r,damage,enemies)=>{for(const e of enemies){if(e.hp<=0||e.targetable===false)continue;const d=Math.hypot(e.x-x,e.y-y);if(d<r+e.r){e.hp-=damage;e.flash=.06}}};
export function initCompanions(p){p.companions??={blade:0,shield:0,ember:0,wisp:0,drone:0};p.companionState??={shots:{},hits:{},shieldCd:0}}
export function updateCompanions(p,dt,enemies,bullets,time){initCompanions(p);const c=p.companions,s=p.companionState;s.shieldCd=Math.max(0,s.shieldCd-dt);
 const orbitCount=c.blade||0;for(let i=0;i<orbitCount;i++){const a=time*(2.3+.08*orbitCount)+i*Math.PI*2/orbitCount,x=p.x+Math.cos(a)*48,y=p.y+Math.sin(a)*48,key=`b${i}`;s.hits[key]??=new Map();for(const e of enemies){if(e.hp<=0||e.targetable===false)continue;const last=s.hits[key].get(e)||0;if(time-last>.32&&Math.hypot(e.x-x,e.y-y)<e.r+9){e.hp-=p.damage*(.38+.07*c.blade);e.flash=.06;s.hits[key].set(e,time)}}}
 if(c.ember){const key="ember";s.shots[key]=(s.shots[key]||0)-dt;if(s.shots[key]<=0){const t=nearest(p.x,p.y,enemies,330);if(t){const a=Math.atan2(t.y-p.y,t.x-p.x),speed=380;bullets.push({kind:"familiar-ember",x:p.x+Math.cos(time*1.7)*30,y:p.y+Math.sin(time*1.7)*30,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:3.5,life:1.6,pierce:0,damage:p.damage*(.42+.08*c.ember)});s.shots[key]=Math.max(.38,1.05-c.ember*.12)}}}
 if(c.wisp){const key="wisp";s.shots[key]=(s.shots[key]||0)-dt;if(s.shots[key]<=0){const t=nearest(p.x,p.y,enemies,260);if(t){damageNear(t.x,t.y,42+c.wisp*5,p.damage*(.24+.06*c.wisp),enemies);bullets.push({kind:"familiar-pulse",x:t.x,y:t.y,vx:0,vy:0,r:18+c.wisp*3,life:.18,pierce:99,damage:0});s.shots[key]=Math.max(.7,1.65-c.wisp*.16)}}}
 if(c.drone){const key="drone";s.shots[key]=(s.shots[key]||0)-dt;if(s.shots[key]<=0){const t=nearest(p.x,p.y,enemies,420);if(t){const a=Math.atan2(t.y-p.y,t.x-p.x),speed=p.bulletSpeed*.82;bullets.push({kind:"familiar-drone",x:p.x+Math.cos(time*.9+2.1)*36,y:p.y+Math.sin(time*.9+2.1)*36,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:3,life:1.8,pierce:Math.min(1,p.pierce),damage:p.damage*(.3+.05*c.drone)});s.shots[key]=Math.max(.3,.92-c.drone*.1)}}}}
}
export function companionDamageMultiplier(p){initCompanions(p);return p.companions.shield?Math.max(.62,1-p.companions.shield*.08):1}
export function companionLabel(p){initCompanions(p);const c=p.companions,n=[];if(c.blade)n.push(`RAZOR ORBIT ${c.blade}`);if(c.shield)n.push(`AEGIS ${c.shield}`);if(c.ember)n.push(`EMBER ${c.ember}`);if(c.wisp)n.push(`WISP ${c.wisp}`);if(c.drone)n.push(`GUNDRONE ${c.drone}`);return n.join(" · ")}
export function drawCompanions(ctx,p,time){if(!p?.companions)return;const c=p.companions;for(let i=0;i<c.blade;i++){const a=time*(2.3+.08*c.blade)+i*Math.PI*2/c.blade,x=p.x+Math.cos(a)*48,y=p.y+Math.sin(a)*48;ctx.save();ctx.translate(x,y);ctx.rotate(a+Math.PI/2);ctx.fillStyle="#fff1a8";ctx.shadowBlur=15;ctx.shadowColor="#ffd95a";ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(5,7);ctx.lineTo(0,4);ctx.lineTo(-5,7);ctx.closePath();ctx.fill();ctx.restore()}if(c.shield){ctx.save();ctx.strokeStyle="#83eaff";ctx.globalAlpha=.25+.08*Math.sin(time*5);ctx.lineWidth=2+c.shield*.5;ctx.beginPath();ctx.arc(p.x,p.y,p.r+14+c.shield*2,0,Math.PI*2);ctx.stroke();ctx.restore()}const fam=[c.ember&&["#ffb45f",time*1.7,30,4],c.wisp&&["#c991ff",time*1.25+2,34,5],c.drone&&["#78ebff",time*.9+2.1,36,5]].filter(Boolean);for(const [color,a,r,size] of fam){ctx.save();ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,size,0,Math.PI*2);ctx.fill();ctx.restore()}}
