const names=`Hot Core|Cold Forge|Redline Coil|Pulse Divider|Rail Accelerator|Dense Slug|Split Bus|Trident Relay|Phase Jacket|Ghost Bore|Lucky Circuit|Loaded Die|Guidance Kernel|Arc Imprint|Nova Imprint|Gravity Anchor|Prism Imprint|Glass Reactor|Gyro Stabilizer|Ion Choke|Reinforced Hull|Titanium Ribs|Emergency Foam|Repair Nanites|Reactive Plating|Ablative Shell|Vector Thrusters|Afterburner|Slipstream|Gravity Well|Signal Harvest|Black Box|Combat Medic|Thin Skin|Heavy Frame|Razor Orbit|Aegis Halo|Ember Familiar|Void Wisp|Gundrone|Saw Moon|Needle Satellite|Halo Shard|Mirror Moon|Storm Sprite|Seeker Sprite|Nova Mote|Gravity Mote|Phase Drone|Fork Drone|Mercury Switch|Copper Heart|Ceramic Fuse|Blue Capacitor|Gold Capacitor|Fat Capacitor|Long Barrel|Short Barrel|Warped Lens|Dead Channel|Live Channel|Spare Bulkhead|Field Rations|Mag Clamp|Data Leech|Hot Wiring|Coolant Loop|Overpressure|Needle Rounds|Soft Rounds|Salvage Map|Combat Telemetry|Shock Mount|Drive Belt|Ballast|Razor Wire|Bright Powder|Dark Powder|Fast Clock|Slow Clock|Spare Reactor|Dirty Reactor|Clean Reactor|Twin Pump|Wide Nozzle|Pinpoint Nozzle|Hunter Array|Surveyor|Vacuum Scoop|Learning Core|Blood Battery|Revenge Relay|Last Bulkhead|Kill Switch|Scrap Feast|Critical Reboot|Phase Memory|Terminal Velocity|Big Bang Board|Echo Chamber|Fork Tax|Ghost Protocol|Arc Battery|Prism Mirror|Anchor Clock|Homing Instinct|Second Opinion|Orbital Foundry|Mutual Defense|Crowded Orbit|Black Sun|White Noise|Needle Storm|Glass Needle|Heavy Phase|Bright Ghost|Seeking Splitter|Storm Lens|Gravity Prism|Nova Guidance|Phase Anchor|Critical Arc|Razor Payload|Razor Velocity|Ember Arc|Wisp Anchor|Drone Fork|Aegis Nova|Familiar Guidance|Orbital Prism|Saint Elmo|Funeral Star|Choir Engine|Event Horizon Chip|Recursive Bus|Prism Rail|Critical Mass Cell|Guardian Network|Moon Court|Dead God Circuit|Rusted Key|Lucky Bolt|Warm Seat|Red Tape|Blue Tape|Green Tape|Spare Spring|Tiny Magnet|Training Manual`.split("|");
if(names.length!==150)throw new Error(`Expected 150 module names, got ${names.length}`);
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const core={
"Hot Core":{damage:1.28,tags:["damage"]},"Redline Coil":{fireRate:.84,tags:["cadence"]},"Rail Accelerator":{bulletSpeed:1.28,tags:["velocity"]},"Dense Slug":{bulletSize:1.3,damage:1.12,tags:["payload"]},"Split Bus":{shots:1,tags:["fork"]},"Trident Relay":{shots:2,damage:.82,tags:["fork"]},"Phase Jacket":{pierce:1,tags:["pierce"]},"Ghost Bore":{pierce:2,bulletSize:.9,tags:["pierce"]},"Lucky Circuit":{crit:.1,tags:["crit"]},"Guidance Kernel":{flags:["missile"],tags:["seek"]},"Arc Imprint":{flags:["arc"],tags:["arc"]},"Nova Imprint":{flags:["nova"],tags:["nova"]},"Gravity Anchor":{flags:["mines"],tags:["anchor"]},"Prism Imprint":{flags:["beam"],tags:["prism"]},"Razor Orbit":{companion:"blade",tags:["orbital"]},"Aegis Halo":{companion:"shield",tags:["orbital","armor"]},"Ember Familiar":{companion:"ember",tags:["familiar"]},"Void Wisp":{companion:"wisp",tags:["familiar","nova"]},"Gundrone":{companion:"drone",tags:["familiar","pierce"]}};
const templates=[{damage:1.14,tags:["damage"]},{fireRate:.9,tags:["cadence"]},{bulletSpeed:1.16,tags:["velocity"]},{bulletSize:1.16,tags:["payload"]},{maxHp:18,tags:["hull"]},{heal:24,tags:["hull"]},{regen:.18,tags:["hull"]},{armor:.045,tags:["armor"]},{speed:1.1,tags:["mobility"]},{magnet:1.3,tags:["economy"]},{xpGain:1.12,tags:["economy"]},{crit:.05,tags:["crit"]},{damage:1.08,bulletSpeed:1.1,tags:["damage","velocity"]},{maxHp:12,armor:.025,tags:["hull","armor"]},{fireRate:.94,speed:1.06,tags:["cadence","mobility"]}];
const specialNames=new Set(["Blood Battery","Revenge Relay","Last Bulkhead","Kill Switch","Scrap Feast","Critical Reboot","Phase Memory","Terminal Velocity","Big Bang Board","Echo Chamber","Fork Tax","Ghost Protocol","Arc Battery","Prism Mirror","Anchor Clock","Homing Instinct","Second Opinion","Orbital Foundry","Mutual Defense","Crowded Orbit","Black Sun","White Noise","Needle Storm","Glass Needle","Heavy Phase","Bright Ghost","Seeking Splitter","Storm Lens","Gravity Prism","Nova Guidance","Phase Anchor","Critical Arc","Razor Payload","Razor Velocity","Ember Arc","Wisp Anchor","Drone Fork","Aegis Nova","Familiar Guidance","Orbital Prism","Saint Elmo","Funeral Star","Choir Engine","Event Horizon Chip","Recursive Bus","Prism Rail","Critical Mass Cell","Guardian Network","Moon Court","Dead God Circuit"]);
const descriptions={damage:"Damage up.",cadence:"Fire rate up.",velocity:"Projectile speed up.",payload:"Projectile mass up.",hull:"Hull integrity up.",armor:"Damage resistance up.",mobility:"Movement speed up.",economy:"Salvage acquisition improved.",crit:"Critical chance up.",fork:"Adds or empowers split volleys.",pierce:"Adds or empowers piercing rounds.",seek:"Adds guidance behavior.",arc:"Adds electrical behavior.",nova:"Adds explosive behavior.",anchor:"Adds gravity behavior.",prism:"Adds prism behavior.",orbital:"Adds an orbital system.",familiar:"Adds a familiar system."};
export const MODULES=names.map((name,i)=>{const base={...(core[name]||templates[i%templates.length])},tags=[...(base.tags||[])];delete base.tags;const special=specialNames.has(name)?slug(name):null;if(special)base.special=special;const rarity=special?(i>129?"SPECIAL":"RARE"):i%11===0?"RARE":i%4===0?"UNCOMMON":"COMMON";const desc=special?`Rule-changing module: ${name} creates a special interaction when its systems line up.`:(tags.map(t=>descriptions[t]).filter(Boolean).join(" ")||"Ship systems improved.");return{id:slug(name),name,desc,effect:base,tags,rarity}});
export const moduleById=id=>MODULES.find(m=>m.id===id);
export function applyModule(p,m){p.items??=new Set();if(p.items.has(m.id))return false;p.items.add(m.id);const e=m.effect||{};for(const k of["damage","fireRate","bulletSpeed","bulletSize","speed","magnet","xpGain"])if(e[k]!=null)p[k]*=e[k];for(const k of["shots","pierce"])if(e[k])p[k]+=e[k];if(e.maxHp){p.maxHp=Math.max(25,p.maxHp+e.maxHp);p.hp=Math.min(p.maxHp,p.hp+Math.max(0,e.maxHp))}if(e.heal)p.hp=Math.min(p.maxHp,p.hp+e.heal);if(e.crit)p.crit=Math.min(.75,p.crit+e.crit);if(e.armor)p.armor=Math.max(0,Math.min(.65,p.armor+e.armor));if(e.regen)p.regen=Math.max(0,p.regen+e.regen);if(e.flags)for(const id of e.flags){p.passives??={};p.passives[id]=1}if(e.companion){p.companions??={};p.companions[e.companion]=(p.companions[e.companion]||0)+1}if(e.special){p.specials??=new Set();p.specials.add(e.special)}p.passives??={};p.passives[m.id]=1;for(const tag of m.tags||[])p.passives[tag]=(p.passives[tag]||0)+1;return true}
const weight=m=>m.rarity==="COMMON"?8:m.rarity==="UNCOMMON"?5:m.rarity==="RARE"?2:.7;
export function randomModules(player,n=3){const owned=player.items||new Set();return MODULES.filter(m=>!owned.has(m.id)).map(m=>({m,k:Math.random()**(1/weight(m))})).sort((a,b)=>b.k-a.k).slice(0,n).map(x=>x.m)}
