export function createFreshPlayer(width, height) {
  return {
    x: width / 2,
    y: height / 2,
    r: 11,
    hp: 100,
    maxHp: 100,
    speed: 245,
    fireRate: 0.42,
    fireCd: 0,
    damage: 18,
    shots: 1,
    pierce: 0,
    bulletSpeed: 520,
    bulletSize: 4,
    magnet: 110,
    regen: 0,
    crit: 0.05,
    armor: 0,
    dashBoost: 0,
    xpGain: 1,
    orbitals: 0,
    invuln: 0,
    boost: 0,
    level: 1,
    xp: 0,
    nextXp: 35,
    overdrive: 0,
    nullified: false,
    shipSides: 3,
    shipColor: "#78ebff",
  };
}
