const active=(p,id)=>(p.passives?.[id]||0)>0||(p.weapons?.[id]||0)>0;
export function blasterTraits(player){
 const fork=active(player,"multishot"),pierce=active(player,"pierce"),payload=active(player,"size"),crit=active(player,"crit"),velocity=active(player,"bullet"),seek=active(player,"missile"),arc=active(player,"arc"),nova=active(player,"nova"),anchor=active(player,"mines"),prism=active(player,"beam");
 return{fork,pierce,payload,crit,velocity,seek,arc,nova,anchor,prism,
  forkedGuidance:fork&&seek,criticalConduction:crit&&arc,massDriver:payload&&velocity,phaseDischarge:pierce&&nova,prismaticPhase:pierce&&prism,
  seekingStorm:fork&&seek&&arc,criticalMass:payload&&crit&&nova,railPrism:velocity&&pierce&&prism,
  recursiveViolence:fork&&pierce&&seek&&arc,eventHorizon:payload&&nova&&anchor&&pierce};
}
const generation=(parent)=>Math.min(3,(parent?.generation||0)+1);
export function decorateBlaster(bullet,player,parent=null){
 const traits=parent?.traits?{...parent.traits}:blasterTraits(player);bullet.traits=traits;bullet.generation=parent?generation(parent):0;bullet.seek=traits.seek;bullet.turn=traits.recursiveViolence?8:traits.forkedGuidance?6.4:4.2;bullet.arc=traits.arc;bullet.nova=traits.nova;bullet.prism=traits.prism;bullet.anchor=traits.anchor;bullet.critHit=parent?.critHit??bullet.damage>player.damage*1.5;bullet.guidanceSlot=Math.abs(Math.round(Math.atan2(bullet.vy,bullet.vx)*11))%3;
 if(traits.massDriver){bullet.damage*=1.22;bullet.knockback=28}
 if(traits.criticalConduction&&bullet.critHit)bullet.arcPower=1.7;
 if(traits.phaseDischarge)bullet.phaseCharge=0;
 if(traits.criticalMass&&bullet.critHit)bullet.novaPower=1.6;
 if(traits.railPrism)bullet.prismPower=1.45;
 if(traits.recursiveViolence){bullet.retarget=true;bullet.inherit=true}
 if(traits.eventHorizon)bullet.eventHorizon=true;
 return bullet
}
const candidates=(b,enemies,exclude=new Set())=>enemies.filter(e=>e.hp>0&&e.targetable!==false&&!exclude.has(e)&&!b.hit?.has(e)).sort((a,c)=>((a.x-b.x)**2+(a.y-b.y)**2)-((c.x-b.x)**2+(c.y-b.y)**2));
export function guidanceTarget(b,enemies){const list=candidates(b,enemies);if(!list.length)return null;const rank=b.traits?.forkedGuidance?Math.min(list.length-1,b.guidanceSlot||0):0;return list[rank]}
function nearestFrom(origin,enemies,exclude=new Set()){let best=null,bd=Infinity;for(const e of enemies){if(e.hp<=0||e.targetable===false||exclude.has(e))continue;const d=(e.x-origin.x)**2+(e.y-origin.y)**2;if(d<bd){bd=d;best=e}}return best}
function chainArc(b,first,enemies,fx){const used=new Set([first]);let origin=first;const count=b.traits?.seekingStorm?4:2,damage=b.damage*.27*(b.arcPower||1),points=[{x:b.x,y:b.y},{x:first.x,y:first.y}];for(let i=0;i<count;i++){const t=nearestFrom(origin,enemies,used);if(!t||Math.hypot(t.x-origin.x,t.y-origin.y)>185)break;used.add(t);t.hp-=damage;t.flash=.08;points.push({x:t.x,y:t.y});origin=t}if(points.length>2)fx.push({kind:"arc",points,life:.14,max:.14,synergy:true})}
function novaImpact(b,e,enemies,fx){const charge=b.traits?.phaseDischarge?Math.min(.8,(b.phaseCharge||0)*.18):0,power=(b.novaPower||1)*(1+charge),radius=(b.eventHorizon?82:56)*power,damage=b.damage*.3*power;for(const t of enemies){if(t===e||t.hp<=0||t.targetable===false)continue;const d=Math.hypot(t.x-e.x,t.y-e.y);if(d<radius){t.hp-=damage*(1-d/radius*.55);t.flash=.07}}fx.push({kind:"nova",x:e.x,y:e.y,radius,life:.2,max:.2,synergy:true})}
function prismImpact(b,e,enemies,fx){const speed=Math.hypot(b.vx,b.vy)||1,dx=b.vx/speed,dy=b.vy/speed,range=135*(b.prismPower||1),width=5*(b.prismPower||1),end={x:e.x+dx*range,y:e.y+dy*range};for(const t of enemies){if(t===e||t.hp<=0||t.targetable===false)continue;const vx=end.x-e.x,vy=end.y-e.y,wx=t.x-e.x,wy=t.y-e.y,c2=vx*vx+vy*vy,q=c2?Math.max(0,Math.min(1,(vx*wx+vy*wy)/c2)):0;if(Math.hypot(t.x-(e.x+q*vx),t.y-(e.y+q*vy))<t.r+width){t.hp-=b.damage*.23*(b.prismPower||1);t.flash=.06}}fx.push({kind:"beam",a:{x:e.x,y:e.y},b:end,width,life:.12,max:.12,synergy:true})}
function childRound(parent,angle,damageScale=.45,speedScale=.9){const speed=Math.max(180,Math.hypot(parent.vx,parent.vy)*speedScale);return{kind:"blaster",x:parent.x,y:parent.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:Math.max(2.2,parent.r*.7),life:1.25,pierce:Math.max(0,Math.min(2,parent.pierce)),damage:parent.damage*damageScale,traits:{...parent.traits},generation:generation(parent),seek:parent.seek,turn:parent.turn,arc:parent.arc,nova:parent.nova,prism:parent.prism,anchor:parent.anchor,critHit:false,guidanceSlot:Math.abs(Math.round(angle*13))%3,inherit:true}}
function fragmentCriticalMass(b,bullets){if(!b.traits?.criticalMass||!b.critHit||b.generation>=2)return;const base=Math.atan2(b.vy,b.vx);for(const offset of [-.48,0,.48])bullets.push(childRound(b,base+offset,.34,.82))}
function recursiveChildren(b,e,bullets){if(!b.traits?.recursiveViolence||b.generation>=2||e.hp>b.damage)return;const base=Math.atan2(b.vy,b.vx);for(const offset of [-.34,.34]){const child=childRound(b,base+offset,.5,.95);child.seek=true;child.turn=9;child.pierce=Math.max(1,child.pierce);bullets.push(child)}}
function seedAnchor(b,e,bullets){if(!b.eventHorizon||b.generation>1||b.pierce>0)return;bullets.push({kind:"synergy-anchor",x:e.x,y:e.y,vx:0,vy:0,r:2,life:.72,timer:.55,pierce:99,damage:0,traits:{...b.traits},generation:generation(b),anchorPower:b.damage*.72,hit:new Set()})}
export function updateSynergyProjectile(b,enemies,dt,weaponFx){
 if(b.kind==="synergy-anchor"){b.timer-=dt;if(b.timer<=0&&!b.detonated){b.detonated=true;const radius=112,damage=b.anchorPower||24;for(const e of enemies){if(e.hp<=0||e.targetable===false)continue;const d=Math.hypot(e.x-b.x,e.y-b.y);if(d<radius){e.hp-=damage*(1-d/radius*.55);e.flash=.1}}weaponFx.push({kind:"nova",x:b.x,y:b.y,radius,life:.3,max:.3,synergy:true});b.life=0}return}
 if(b.kind!=="blaster"||!b.seek)return;const t=guidanceTarget(b,enemies);if(!t)return;const speed=Math.max(1,Math.hypot(b.vx,b.vy)),current=Math.atan2(b.vy,b.vx),desired=Math.atan2(t.y-b.y,t.x-b.x),delta=((desired-current+Math.PI*3)%(Math.PI*2))-Math.PI,next=current+Math.max(-b.turn*dt,Math.min(b.turn*dt,delta));b.vx=Math.cos(next)*speed;b.vy=Math.sin(next)*speed
}
export function onSynergyHit(b,e,{enemies,weaponFx,bullets}){if(b.kind!=="blaster"||!b.traits)return;b.phaseCharge=(b.phaseCharge||0)+1;if(b.arc)chainArc(b,e,enemies,weaponFx);if(b.nova)novaImpact(b,e,enemies,weaponFx);if(b.prism)prismImpact(b,e,enemies,weaponFx);if(b.knockback&&!e.boss){const d=Math.max(1,Math.hypot(e.x-b.x,e.y-b.y));e.x+=((e.x-b.x)/d)*b.knockback;e.y+=((e.y-b.y)/d)*b.knockback}fragmentCriticalMass(b,bullets);recursiveChildren(b,e,bullets);seedAnchor(b,e,bullets)}
export function synergyLabel(player){const t=blasterTraits(player),names=[];if(t.recursiveViolence)names.push("RECURSIVE VIOLENCE");else if(t.seekingStorm)names.push("SEEKING STORM");else{if(t.forkedGuidance)names.push("FORKED GUIDANCE");if(t.criticalConduction)names.push("CRITICAL CONDUCTION")}if(t.eventHorizon)names.push("EVENT HORIZON");if(t.criticalMass)names.push("CRITICAL MASS");if(t.railPrism)names.push("RAIL PRISM");else if(t.prismaticPhase)names.push("PRISMATIC PHASE");if(t.phaseDischarge&&!t.eventHorizon)names.push("PHASE DISCHARGE");if(t.massDriver)names.push("MASS DRIVER");return names.join(" · ")}
