import {decorateBlaster,updateSynergyProjectile,onSynergyHit,synergyLabel} from "./synergies.js";
import {initCompanions,updateCompanions,companionLabel,drawCompanions} from "./companions.js";
const distToSegment=(p,a,b)=>{const vx=b.x-a.x,vy=b.y-a.y,wx=p.x-a.x,wy=p.y-a.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy,t=c2?Math.max(0,Math.min(1,c1/c2)):0,dx=p.x-(a.x+t*vx),dy=p.y-(a.y+t*vy);return Math.hypot(dx,dy)};
export function initWeapons(player){player.weapons={missile:0,arc:0,nova:0,mines:0,beam:0};player.weaponEvolved={missile:false,arc:false,nova:false,mines:false,beam:false};player.passives={};player.weaponCd={};player.weaponFx=[];initCompanions(player)}
export function weaponLabel(player){if(!player)return"BLASTER ONLY";const synergy=synergyLabel(player),companions=companionLabel(player),parts=[companions,synergy].filter(Boolean);return parts.length?`BLASTER · ${parts.join(" · ")}`:"BLASTER ONLY"}
export function updateWeapons(player,dt,enemies,bullets,particles,time){if(!player)return;globalThis.__orbitalSynergyPlayer=player;player.weaponFx=player.weaponFx.filter(f=>(f.life-=dt)>0);updateCompanions(player,dt,enemies,bullets,time)}
function predictedImpact(b,e,dt){const next={x:b.x+b.vx*dt,y:b.y+b.vy*dt};return distToSegment(e,b,next)<=(b.r||0)+e.r}
export function updateWeaponProjectiles(bullets,enemies,dt){const player=globalThis.__orbitalSynergyPlayer;for(const b of bullets){if(!player)continue;if(b.kind==="blaster"&&!b.traits)decorateBlaster(b,player);if(b.kind!=="blaster"&&b.kind!=="synergy-anchor")continue;updateSynergyProjectile(b,enemies,dt,player.weaponFx);if(b.kind!=="blaster")continue;b.synergyHits??=new Set();for(const e of enemies){if(e.hp<=0||e.targetable===false||b.synergyHits.has(e))continue;if(predictedImpact(b,e,dt)){b.synergyHits.add(e);onSynergyHit(b,e,{enemies,weaponFx:player.weaponFx,bullets})}}}}
export function drawWeaponFx(ctx,player){if(!player)return;drawCompanions(ctx,player,performance.now()/1000);for(const f of player.weaponFx||[]){const alpha=Math.max(0,f.life/f.max);ctx.save();ctx.globalAlpha=alpha;if(f.kind==="arc"){ctx.strokeStyle=f.synergy?"#ffe977":"#b9f7ff";ctx.shadowColor=f.synergy?"#ffd84d":"#78eaff";ctx.shadowBlur=24;ctx.lineWidth=2.5;ctx.beginPath();f.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else if(f.kind==="nova"){ctx.strokeStyle=f.synergy?"#ff8fcf":"#d69cff";ctx.shadowColor=f.synergy?"#ff5dbb":"#b675ff";ctx.shadowBlur=24;ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,f.radius*(1.1-alpha*.1),0,Math.PI*2);ctx.stroke()}else if(f.kind==="beam"){ctx.strokeStyle="#bafcff";ctx.shadowColor="#72eaff";ctx.shadowBlur=20;ctx.lineWidth=f.width*alpha;ctx.beginPath();ctx.moveTo(f.a.x,f.a.y);ctx.lineTo(f.b.x,f.b.y);ctx.stroke();ctx.strokeStyle="#fff";ctx.lineWidth=Math.max(1,f.width*.18);ctx.stroke()}ctx.restore()}}
